services:
  - type: web
    name: resume-backend
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://localhost:5432/resume_builder
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: soniSQL@123
      - key: API_KEY
        value: MlQpO64ZF27xYuS5cs0YL4qbOfGubnlL