spring.datasource.url=jdbc:postgresql://localhost:5432/resume_builder
spring.datasource.username=postgres
spring.datasource.password=soniSQL@123


spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
server.tomcat.max-http-form-post-size=0
server.tomcat.connection-timeout=30s
spring.codec.max-in-memory-size=10MB 
